### ISSUE TITLE
npm run build ends with an error message if a subdirectory is in data/shortcuts

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#330]
```
/var/www/html/trovu/src/js/modules/DataManager.js:1
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:748:3)
    at tryReadSync (node:fs:448:20)
    at Proxy.readFileSync (node:fs:494:19)
    at DataManager.readYmls (/var/www/html/trovu/src/js/modules/DataManager.js:101:22)
    at DataManager.load (/var/www/html/trovu/src/js/modules/DataManager.js:13:37)
    at Command.compileData (/var/www/html/trovu/src/js/cli.js:65:28)
    at Command.listener [as _actionHandler] (/var/www/html/trovu/node_modules/commander/lib/command.js:494:17)
    at /var/www/html/trovu/node_modules/commander/lib/command.js:1296:65
    at Command._chainOrCall (/var/www/html/trovu/node_modules/commander/lib/command.js:1193:12)
    at Command._parseCommand (/var/www/html/trovu/node_modules/commander/lib/command.js:1296:27) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

Node.js v18.13.0
created dist/public/ in 9.4s
```

**Comment by Wikinaut** [comment]
Solved. The problem is, that `npm run build` fails, if there is a subdirectory in `data/shortcuts`.
