### ISSUE TITLE
build error: [!] (plugin html) TypeError: Cannot read properties of undefined (reading 'blog')

### ISSUE THREAD

**Issue by Wikinaut** [trovu/trovu#434]
```
src/js/index.js → dist/public/...
[!] (plugin html) TypeError: Cannot read properties of undefined (reading 'blog')
TypeError: Cannot read properties of undefined (reading 'blog')
    at templateFunc (/var/www/html/trovu/rollup.config.js:73:27)
    at Object.generateBundle (/var/www/html/trovu/node_modules/@rollup/plugin-html/dist/index.js:85:34)
    at /var/www/html/trovu/node_modules/rollup/dist/shared/rollup.js:18971:25
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #434</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @Wikinaut</code> (replace <code>20</code> with the amount, and <code>@Wikinaut</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by Wikinaut** [comment]
invalid. closed.

(was a temporary problem while I edited my local trovu.config.default.yml)
